apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::149581614588:role/UdacityFlaskDeployCBKubectlRole
      username: build  
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::149581614588:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-QR7V4AJ3NMWT
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2023-05-15T14:18:48Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2008"
  uid: b440e609-f5e2-4699-977f-9128b6ff3821
