apiVersion: v1
data:
  mapRoles: "- groups:\n  - system:masters\n  rolearn: arn:aws:iam::149581614588:role/UdacityFlaskDeployCBKubectlRole\n
    \ username: build  \n- groups:\n  - system:bootstrappers\n  - system:nodes\n  rolearn:
    arn:aws:iam::149581614588:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-QR7V4AJ3NMWT\n
    \ username: system:node:{{EC2PrivateDNSName}}\n"
kind: ConfigMap
metadata:
  creationTimestamp: "2023-05-15T14:18:48Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "219990"
  uid: b440e609-f5e2-4699-977f-9128b6ff3821
